spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 336370060789-pm29lll51ucnke4vk8lgdvrkh7nmq2la.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: n2hPVumLJt_V3qwG3lUJ
            client-secret: b5tOAQ5QGL
            redirect-uri: http://localhost:8081/login/oauth2/code/naver # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: 90d0312319c978b62229bc46af04581c
            client-secret: xYYPuhGcF9sCHnaLbicuNe3qvBcn6s7d
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: POST
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id