server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    #include: db
    include: oauth
  
  jpa:
    show-sql: true  #P6spy와 함께, SQL 로그도 보도록 하겠습니다..! 안해주셔도 무방합니다만, P6spy가 너무 안 이쁘게 보여줘서...ㅠㅠ
    
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
    hibernate:
      #ddl-auto: create
      ddl-auto: none
      
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
        
        default_batch_fetch_size: 500 #배치 사이즈 (Collection 조회 최적화)
        
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 336370060789-pm29lll51ucnke4vk8lgdvrkh7nmq2la.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: n2hPVumLJt_V3qwG3lUJ
            client-secret: b5tOAQ5QGL
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: 90d0312319c978b62229bc46af04581c
            client-secret: xYYPuhGcF9sCHnaLbicuNe3qvBcn6s7d
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: POST
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
    
logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    com:
      board:
        demo: info
        
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa